# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cfc3c39b1baba4599610c6ff5794090d2c05caa72025604f6301c56d4bf9cc34c8b12394e2b367f0c44b3ca7b412d60cd233678c0738a1518fccf090b6072b8

test:
  secret_key_base: 94a45bac5400c7554c8b3d2d8c2c62b69a091774197b92dde0d675ce1d820eee5d6da30f7c61e62e2d3151b2fe7a7b1ccd998a0a5786b822b9d8deffa627a288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
